### PR TITLE
in meetingControls.jsx i have upadted leaveroom logic to ask a confir…

### PR DESCRIPTION
**Pull request by nigdifg**
confirmation from user to leave meet!

### CODE REVIEW

**Review by Ayanabha1 — CHANGES_REQUESTED** [review]
Please remove package.json and package-lock.json from staged files and then push.
Please only push the file you have worked on

**Review by nigdifg — COMMENTED** [review]
Please find updated changes!

**Review by Ayanabha1 — APPROVED** [review]
Looks good ✅

**Comment by Ayanabha1** [comment]
Thanks for your contribution :)
The changes are now active in the production environment.
image

**Pull request merged**
